### ISSUE TITLE
Failed pipeline build; image template stuck in "canceling" state

### ISSUE THREAD

**Issue by ejm5204** [danielsollondon/azvmimagebuilder#116] opened 2021-06-02 11:20 UTC
![image](https://user-images.githubusercontent.com/55196247/120471113-4f5b3e80-c372-11eb-8966-a2bd0f186cde.png)

I'm having an issue where a pipeline build hit the 60 minute time limit and failed. The image builder resource group was left for troubleshooting as normal so I could look through for any problems. When I was done and tried to use the remove-AzImageBuilderTemplate command, I received this:

> Remove-AzImageBuilderTemplate_Delete: Operation Microsoft.VirtualMachineImages/imageTemplates/delete is not allowed in provisioning state: provisioned or run state: canceling.

I went to the image template to check on it and the template provisioning state said "succeeded" but the build run state was still "building". I clicked "Stop Build" so I could remove the image template and run another pipeline, but the image template is now stuck in "canceling image build". I stayed like this for several days so I tried removing the IT_ resource group and it changed nothing. Using az image builder delete in the azure cli doesn't work.

**Comment by djpierson** [comment] 2021-06-04 23:31
I also have this same issue

**Comment by djpierson** [comment] 2021-06-17 15:11
Any update on this now its GA? I have a resource that I'm unable to delete. Cant even delete the entire RG to get rid of it

**Comment by ejm5204** [comment] 2021-06-17 15:13
@djpierson I ended up making a support ticket with Azure for them to reset the provisioning state and then I was able to delete. The process will take a few days as they try to figure out what caused the original problem before they resort to just resetting it. No other solution that I found so far.

**Comment by ii-batman** [comment] 2021-06-17 15:17
> Any update on this now its GA? I have a resource that I'm unable to delete. Cant even delete the entire RG to get rid of it

If my AIB build fails, then I can go to my RG (where the template and ID and SIG are) > go to the template (IT_1234xxxx) > Stop or cancel > wait a bit and the Temp IT_xxxx will auto delete.

Try it or maybe I am not talking about the same thing?

**Comment by djpierson** [comment] 2021-06-17 16:43
Failed ones delete fine. Its a build stuck in the cancelling state which cannot be removed

**Comment by MarkWilsonDLG** [comment] 2021-07-13 17:33
I have this as well

**Comment by ld0614** [comment] 2021-09-27 14:24
I also ran into this issue which was resolved by the support engineer requesting a reset of the status from the Product Group.

It was ticket 2109100050000410 if anyone finds it helpful 😄

**Comment by ld0614** [comment] 2021-09-27 14:33
Duplicate of #48

**Comment by modios** [comment] 2021-09-28 09:03
Same problem here.

**Closed as completed** 2023-12-06 04:59 UTC
